---
title: "Input Output Model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Input Output Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lpsugar)
library(ROI.plugin.highs)
```

Make up some data

```{r}
sector <- c("Agriculture", "Industry", "Services")

z <- c(
    400, 100, 150,
    350, 900, 200,
    250, 500, 800
) |> parameter(sector, sector)

va <- c(400, 600, 200) |> parameter(sector)
demand <- c(500, 200, 700) |> parameter(sector)
emissions <- c(400, 900, 50) |> parameter(sector)
output <- colSums(z) + va
```

Calculate relatives

```{r}
a <- z
relative_va <- va / output
relative_emissions <- emissions / output

for (j in sector) {
    a[, j] <- z[, j] / output[j]
}
```

Make up some parameters.

```{r}
min_a <- a * 0.8
coef <- 0 |> parameter(sector, sector)

for (j in sector) {
    importance <- runif(3)
    importance <- importance / sum(importance)
    coef[, j] <- importance / a[, j]
}

penalty <- c(0.05, 0.01, 0.04) |> parameter(sector)
```

Model

```{r}
io <- lp_problem() |> 
    lp_variable(
        z[sector, sector],
        lower = 0
    ) |> 
    # lp_alias_manual(
    #     output[sector], 
    #     for (j in sector) {
    #         output[j] = sum_over(i = sector, coef[i, j] * z[i, j]) - penalty[j] * sum(emissions)
    #     }
    # ) |> 
    lp_alias(
        output = colSums(coef * z) - penalty * sum(emissions)
    ) |> 
    lp_alias(
        emissions = output * relative_emissions
    ) |> 
    lp_minimize(
        sum(emissions)
    ) |> 
    lp_constraint(
        for (i in seq_along(sector)) {
            sum(z[i, ]) + demand[i] == output[i]
        },
        for (i in seq_along(sector)) for (j in seq_along(sector)) {
            z[i, j] >= min_a[i, j] * output[j]
        }
    )

io_solution <- lp_solve(io, solver = "highs")
```

Improvement!

```{r}
sum(emissions)
sum(io_solution$aliases$emissions)
```

## Model With Different Production Techniques

```{r}
library(dplyr)

random_technique <- function(produces) {
    list(
        produces = produces,
        inputs = runif(3, min = 2, max = 8) |> 
            parameter(sector) |> 
            round() |> 
            list(),
        output = runif(1, min = 8, max = 25) |> 
            round(),
        emissions = 30 * rexp(1),
        variable_cost = 50 * rexp(1),
        fix_cost = 200 * rexp(1)
    )
}

produces <- c(
    rep("Agriculture", 2),
    rep("Industry", 4),
    rep("Services", 3)
)

tech_df <- purrr::map_df(produces, random_technique)
tech_df

tech <- 1:nrow(tech_df)
inputs <- bind_rows(tech_df$inputs) |> as.matrix()
output <- tech_df$output

emissions <- tech_df$emissions
variable_cost <- tech_df$variable_cost 
fix_cost <- tech_df$fix_cost
```


```{r}
io2 <- lp_problem() |> 
    lp_variable(
        usage[tech],
        integer = TRUE,
        lower = 0
    ) |> 
    lp_variable(
        any_usage[tech],
        binary = TRUE
    ) |> 
    lp_alias_manual(
        total_output[sector], for (j in sector) {
            tj <- which(produces == j)
            total_output[j] = sum_over(t = tj, usage[t] * output[t])
        }
    ) |> 
    lp_alias_manual(
        spent[sector], for (j in sector) {
            spent[j] = sum_over(t = tech, usage[t] * inputs[t, j])
        }
    ) |> 
    lp_alias(
        # Per sector
        final_supply = total_output - spent,
        # Per tech
        tech_cost = fix_cost * any_usage + variable_cost * usage,
        tech_emissions = emissions * usage
    ) |> 
    lp_constraint(
        for (t in tech) usage[t] <= 1000 * any_usage[t],
        for (t in tech) any_usage[t] <= usage[t],
        for (j in sector) final_supply[j] >= demand[j]
    )
```


```{r}
io2_min_cost <- io2 |> 
    lp_minimize(sum(tech_cost)) |> 
    lp_solve(solver = "highs")

io2_min_emissions <- io2 |> 
    lp_minimize(sum(tech_emissions)) |> 
    lp_solve(solver = "highs")

solution_data <- function(solution) {
    c(cost = sum(solution$aliases$tech_cost),
      emissions = sum(solution$aliases$tech_emissions),
      total_output = sum(solution$aliases$total_output))
}

cbind(min_cost = solution_data(io2_min_cost),
      min_emissions = solution_data(io2_min_emissions))
```

```{r}
io2_min_cost$variables$usage |> round()
io2_min_emissions$variables$usage |> round()
```


```{r}
io2_min_cost$aliases
io2_min_emissions$aliases
```

